# ---------------------------------------------------------------------------
#
#   Reference
#     - https://www.appveyor.com/docs/appveyor-yml/
#
# ---------------------------------------------------------------------------
version: 1.0.{build}

clone_depth: 2
max_jobs: 4

# ----- Notification ----- 

notifications:
  - provider: Email
    to:
      - luncliff@gmail.com

# ----- Build Matrix ----- 

image: 
  - Visual Studio 2017

platform: 
  # - x86
  - x64

configuration:
  - Debug
  - Release

environment:
  matrix:
    - compiler: msvc

matrix:
  fast_finish: true

# ----- Build steps for each environment ----- 

for:
-
  # MSVC & Visual Studio
  matrix:
    only:
      - compiler: msvc
  install:
    - ps: Write-Host $env:APPVEYOR_BUILD_FOLDER 
    - ps: cmake --version # choco install cmake | out-null
  before_build:
    - ps: Write-Host $env:PLATFORM $env:CONFIGURATION
    - ps: ./Scripts/win-setup.ps1;
  build_script:
    - ps: ./Scripts/win-build.ps1 -InstallPath .\Solved\ -BuildType Debug -BuildShared $False;
  after_build:
    # Rename the variable for build output
    - ps: if( $env:PLATFORM -eq "x86" ){ $env:PLATFORM="Win32"; }
  before_test:
    - ps: $Dir= "$env:APPVEYOR_BUILD_FOLDER/Solved/"
    - ps: $Params="--reporter compact"
  test_script:
    - ps: ./Scripts/run-test.ps1 -Path $Dir -TestParams $Params
